#!/usr/bin/env bash
set -euo pipefail

if [[ -f .env ]]; then
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
fi

SUPABASE_URL="${SUPABASE_URL:-}"
SUPABASE_ANON_KEY="${SUPABASE_ANON_KEY:-${SUPABASE_PUB_KEY:-}}"

python3 - "$SUPABASE_URL" "$SUPABASE_ANON_KEY" > static/config.js <<'PY'
import json
import sys

url = sys.argv[1].rstrip("/")
key = sys.argv[2]

for suffix in ("/rest/v1", "/rest/v1/"):
    if url.endswith(suffix):
        url = url[: -len(suffix)]
        break

print("// Generated by scripts/write-web-config.sh from SUPABASE_URL and SUPABASE_ANON_KEY.")
print("// static/config.js is ignored by git.")
print("window.SUPABASE_URL = " + json.dumps(url) + ";")
print("window.SUPABASE_ANON_KEY = " + json.dumps(key) + ";")
PY

if [[ -z "$SUPABASE_URL" || -z "$SUPABASE_ANON_KEY" ]]; then
  echo "warning: SUPABASE_URL or SUPABASE_ANON_KEY is empty; community cloud will stay disabled" >&2
fi
